schema_version: 1
cameras:
  - id: front
    enabled: true
    backend: realsense
    device_type: d405
    serial_no: REPLACE_FRONT_D405_SERIAL
    namespace: front
    camera_name: camera
    width: 640
    height: 480
    fps: 30
    color_format: RGB8
    depth_format: Z16
    pointcloud: true
    align_depth: false
    sync_rgb_depth: true
    timestamp_alignment: true
    max_actual_exposure_us: 5000
    rgbd_max_midpoint_skew_ms: 1.0
    camera_max_error_ms: 1.0
    required: true
    depth_auto_exposure: true
    depth_exposure_us: 4500
    depth_gain: 64
    depth_auto_exposure_limit_us: 4500
    depth_auto_gain_limit: 64
    color_auto_exposure: false
    color_exposure_us: 4500
    color_gain: 64
    parameters: {}
  - id: left
    enabled: true
    backend: realsense
    device_type: d405
    serial_no: REPLACE_LEFT_D405_SERIAL
    namespace: left
    camera_name: camera
    width: 640
    height: 480
    fps: 30
    color_format: RGB8
    depth_format: Z16
    pointcloud: false
    align_depth: false
    sync_rgb_depth: true
    timestamp_alignment: true
    max_actual_exposure_us: 5000
    rgbd_max_midpoint_skew_ms: 1.0
    camera_max_error_ms: 1.0
    required: true
    depth_auto_exposure: true
    depth_exposure_us: 4500
    depth_gain: 64
    depth_auto_exposure_limit_us: 4500
    depth_auto_gain_limit: 64
    color_auto_exposure: false
    color_exposure_us: 4500
    color_gain: 64
    parameters: {}
  - id: right
    enabled: true
    backend: realsense
    device_type: d435
    serial_no: REPLACE_RIGHT_D435_SERIAL
    namespace: right
    camera_name: camera
    width: 640
    height: 480
    fps: 30
    color_format: RGB8
    depth_format: Z16
    pointcloud: false
    align_depth: false
    sync_rgb_depth: true
    timestamp_alignment: true
    max_actual_exposure_us: 5000
    rgbd_max_midpoint_skew_ms: 1.0
    camera_max_error_ms: 1.0
    required: true
    depth_auto_exposure: false
    depth_exposure_us: 3900
    depth_gain: 64
    depth_auto_exposure_limit_us: 4500
    depth_auto_gain_limit: 128
    color_auto_exposure: false
    color_exposure_us: 3900
    color_gain: 64
    depth_auto_gain: true
    color_auto_gain: true
    color_auto_gain_limit: 128
    parameters: {}
